<?php

include('./variables.php');
include('./constant.php');
include('./variable-quiz.php');
include('./string.php');
include('./string-quiz.php');
include('./number.php');
include('./operators.php');
include('./number-quiz.php');
include('./conditionals.php');
include('./conditional-quiz.php');
include('./arrays.php');
include('./array-quiz.php');
include('./forloop.php');
include('./whileloop.php');
include('./dowhileloop.php');
include('./foreachloop.php');
include('./function.php');
include('./function-quiz.php');
include('./require.php');
